### ISSUE TITLE
Links for downloading datasets, NUS_WIDE and OPENIMage

### ISSUE THREAD

**Issue by JasonLiu-Dr** [akshitac8/Generative_MLZSL#2]
Thanks for your work! could you please provide a link for downloading relevant datasets?

**Comment by akshitac8** [comment]
Hello @JasonLiu-Dr 
For NUS-WIDE, you can download the full dataset by submitting a form mentioned [here](https://lms.comp.nus.edu.sg/wp-content/uploads/2019/research/nuswide/NUS-WIDE.html).
For open-images, you can download the dataset using the script mentioned [here](https://github.com/hbdat/cvpr20_LESA/blob/master/download_imgs/asyn_image_downloader.py)
For MS-COCO, you can download the dataset details mentioned [here](https://github.com/salman-h-khan/PL-ZSD_Release)

**Comment by aliman80** [comment]
link: https://drive.google.com/file/d/1LaCDkLY4XnkB5901OwRTdjOxCRvtDbfP/view?usp=sharing

I am trying this but its not working please resolve if possible
