### ISSUE TITLE
Memory problem

### ISSUE THREAD

**Issue by Enrinz** [akshitac8/Generative_MLZSL#3]
Thanks for code. How could i fix this problem? I also tried to reduce the number of batch size to 32 and 16 but the issue is the same.
![image](https://user-images.githubusercontent.com/86098337/124348182-c4779900-dbe8-11eb-870b-e58cf081875a.png)

**Comment by akshitac8** [comment]
How much GPU memory do you have?

**Comment by Enrinz** [comment]
the dedicaded gpu has 4gb

**Comment by akshitac8** [comment]
The dedicated GPU memory is small for loading the NUS-WIDE features you need to compress the current features using compressed h5 operation and then try to use it

**Comment by Enrinz** [comment]
Alright, I'll try. Thanks
