### ISSUE TITLE
get_extract_data not defined

### ISSUE THREAD

**Issue by Youmna-Salah** [akshitac8/Generative_MLZSL#4]
Hello!
I was using your 'extract_4095_features.py' binary when I realized that the 'get_extract_data' function is not imported or defined. could you please provide implementation or import for this function?

**Comment by akshitac8** [comment]
Hello @Youmna-Salah, Can you check now?

**Comment by akshitac8** [comment]
@Youmna-Salah is the issue solved?

**Comment by Youmna-Salah** [comment]
@akshitac8 yes, thanks for the prompt reply and the fix!
