### ISSUE TITLE
Google drive link not working

### ISSUE THREAD

**Issue by chinmay5** [akshitac8/Generative_MLZSL#5]
Thank you for the wonderful codebase. However, the google drive link for getting the shared folders is not working and seems to have expired. I was struggling a bit with the word embeddings file essentially.

The `NUS_WIDE_pretrained_w2v_glove-wiki-gigaword-300`

**Comment by dgbarclay** [comment]
@chinmay5 were you ever able to access this file? I have searched but have found nothing (@akshitac8)
