### ISSUE TITLE
dataset issue

### ISSUE THREAD

**Issue by hlsfin** [akshitac8/Generative_MLZSL#8]
anyone else having issues accessing the datasets? Thank you

**Comment by akshitac8** [comment]
@hlsfin Can you please explain the issue?

**Comment by hlsfin** [comment]
Oh sorry for not being verbose, I'm having issues with downloading NUS-WIDE dataset, using "https://drive.google.com/file/d/1LaCDkLY4XnkB5901OwRTdjOxCRvtDbfP/view?usp=sharing" link. I get a 'Sorry, the file you have requested does not exist.' error.

**Comment by shujonnaha** [comment]
Same here.

**Comment by akshitac8** [comment]
Hello @hlsfin @shujonnaha the training features are available for downloading at the webpage: https://akshitac8.github.io/GAN_MLZSL/ 
Please let me know if the problem still persists.

**Comment by shujonnaha** [comment]
Thank you so much!
