### ISSUE TITLE
Classification Results/Detection Results 

### ISSUE THREAD

**Issue by aliman80** [akshitac8/Generative_MLZSL#9]
Hi, I have run the code and now i am looking forward to reproduce the classification as well as detection results , Can you provide me access to code for classification results plotting as well as detection part. Also how to test it separately for only ALF scheme or FLF scheme without CLF .Thanks alot

**Comment by akshitac8** [comment]
Hello @aliman80 the classification results are computed using the classifier.py code which is uploaded in the reposistory. For the detection results, I used the code uploaded here : https://github.com/nasir6/zero_shot_detection. 
For testing it seperately as it is mentioned in the paper CLF is a combination of ALF and FLF. The results of both the modules can be reproduced from the repository by making changes to the codebase.

**Comment by aliman80** [comment]
> Hello @aliman80 the classification results are computed using the classifier.py code which is uploaded in the reposistory. For the detection results, I used the code uploaded here : https://github.com/nasir6/zero_shot_detection. For testing it seperately as it is mentioned in the paper CLF is a combination of ALF and FLF. The results of both the modules can be reproduced from the repository by making changes to the codebase. Please check the arguments early fusion and Late fusion mentioned in the config file for the same.

Thank you very much for your reply, i believe my questions are too naive for your expertise level but thanks alot. 
Now i am just wondering why my results are in the range of mAP zsl 6.7 and GZSL 21-22. Thanks alot
